services:
  - type: web
    name: mypockit-backend
    env: java
    rootDir: backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/expenseTracker-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: APP_USER_PROFILE_UPLOAD_DIR
        value: /tmp/uploads

