services:
  - type: web
    name: expenses-backend
    env: docker
    repo: .
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql:3306/expenses_tracker?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: 123456789
      - key: PORT
        value: 8080

  - type: pserv
    name: mysql
    plan: starter
    env: docker
    dockerfilePath: ./mysql/Dockerfile
    autoDeploy: true
    disk:
      name: mysql-volume
      mountPath: /var/lib/mysql
      sizeGB: 5
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: 123456789
      - key: MYSQL_DATABASE
        value: expenses_tracker
